"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { LanguageCode } from '@/types';

export type ShortLangCode = 'hi' | 'en' | 'ta' | 'te' | 'bn' | 'mr' | 'gu';

export interface LanguageOption {
  code: ShortLangCode;
  bcp47: LanguageCode;
  label: string;
  nativeName: string;
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'hi', bcp47: 'hi-IN', label: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'en', bcp47: 'en-IN', label: 'English', nativeName: 'English (Indian)' },
  { code: 'ta', bcp47: 'ta-IN', label: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', bcp47: 'te-IN', label: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', bcp47: 'bn-IN', label: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', bcp47: 'mr-IN', label: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', bcp47: 'gu-IN', label: 'Gujarati', nativeName: 'ગુજરાતી' },
];

export const TRANSLATIONS: Record<ShortLangCode, Record<string, string>> = {
  hi: {
    APP_NAME: 'हमसफ़र',
    APP_SUBTITLE: 'वरिष्ठ सेवा • HUMSAFAR',
    MEDICINES: 'दवाइयां',
    MEDICINES_SUB: 'दवाइयां लें और ट्रैक करें',
    PAY_BILLS: 'बिल भुगतान',
    PAY_BILLS_SUB: 'सुरक्षित बिजली व पानी बिल',
    CALL_FAMILY: 'परिवार से बात करें',
    CALL_FAMILY_SUB: '1-टच स्पीड डायलर',
    CHECK_SCAM: 'संदेश जांचें',
    CHECK_SCAM_SUB: 'AI स्कैम सुरक्षा कवच',
    SOS: 'आपातकालीन सहायता (SOS)',
    SOS_SUB: 'परिवार को तुरंत अलर्ट भेजें',
    BACK: 'वापस',
    SWITCH_ROLE: 'बदलें (Switch)',
    VOICE_ON: 'आवाज़ चालू है',
    VOICE_OFF: 'आवाज़ बंद है',
    AVAILABLE: 'उपलब्ध',
    BUSY: 'व्यस्त',
    TAKEN: 'दवा ले ली',
    PENDING: 'बाकी है',
    OVERDUE: 'समय समाप्त',
    SAFE: 'सुरक्षित',
    SUSPICIOUS: 'संदेहास्पद',
    CRITICAL: 'खतरनाक ठगी!',
    I_TOOK_IT: 'मैंने दवा ले ली',
    TAP_TO_CALL: 'कॉल करें',
    TAP_TO_VIDEO: 'वीडियो कॉल',
    VERIFY_MESSAGE: 'संदेश जांचें',
    UPLOAD_PHOTO: 'फोटो लगाएं',
    PAY_NOW: 'सुरक्षित भुगतान करें',
    CANCEL_SOS: 'मैं सुरक्षित हूँ (SOS बंद करें)',
    LISTEN_CMD: 'बोलकर बताएं',
    ADD_MEDICINE: 'नई दवा जोड़ें',
    GUARD_CAP: '₹3,000 सुरक्षा कैप सक्रिय',
    GREETING: 'नमस्ते दादाजी! आपका हमसफ़र तैयार है।',
    ALL_SLOTS: 'सभी समय',
    MORNING: 'सुबह',
    AFTERNOON: 'दोपहर',
    EVENING: 'शाम',
    NIGHT: 'रात',
    NO_MEDS: 'इस समय के लिए कोई दवा नहीं है।',
    SCAM_PLACEHOLDER: 'संदेश, एसएमएस या कॉल की बात यहाँ लिखें या बोलें...',
    BILL_ELECTRICITY: 'बिजली बिल',
    BILL_WATER: 'पानी का बिल',
    BILL_GAS: 'गैस सिलेंडर',
    BILL_PHONE: 'मोबाइल व लैंडलाइन',
    CONFIRM_PIN: 'अपना 4-अंकों का गुप्त पिन डालें',
  },
  en: {
    APP_NAME: 'HUMSAFAR',
    APP_SUBTITLE: 'Senior Care Companion',
    MEDICINES: 'Medicines',
    MEDICINES_SUB: 'Schedule & pill reminders',
    PAY_BILLS: 'Pay Bills',
    PAY_BILLS_SUB: 'Safe utility payments',
    CALL_FAMILY: 'Call Family',
    CALL_FAMILY_SUB: '1-touch speed dialer',
    CHECK_SCAM: 'Check Scam',
    CHECK_SCAM_SUB: 'AI Fraud Shield',
    SOS: 'EMERGENCY SOS',
    SOS_SUB: 'Broadcast live alert to family',
    BACK: 'Back',
    SWITCH_ROLE: 'Switch Portal',
    VOICE_ON: 'Voice Reading On',
    VOICE_OFF: 'Voice Reading Off',
    AVAILABLE: 'Available',
    BUSY: 'Busy',
    TAKEN: 'Taken',
    PENDING: 'Pending',
    OVERDUE: 'Overdue',
    SAFE: 'Safe',
    SUSPICIOUS: 'Suspicious',
    CRITICAL: 'Dangerous Scam!',
    I_TOOK_IT: 'I Took It',
    TAP_TO_CALL: 'Voice Call',
    TAP_TO_VIDEO: 'Video Call',
    VERIFY_MESSAGE: 'Analyze Message',
    UPLOAD_PHOTO: 'Upload Photo',
    PAY_NOW: 'Pay Safely',
    CANCEL_SOS: 'I Am Safe (Cancel SOS)',
    LISTEN_CMD: 'Voice Search',
    ADD_MEDICINE: 'Add Medicine',
    GUARD_CAP: '₹3,000 Safety Cap Active',
    GREETING: 'Welcome! Your Humsafar companion is ready.',
    ALL_SLOTS: 'All Times',
    MORNING: 'Morning',
    AFTERNOON: 'Afternoon',
    EVENING: 'Evening',
    NIGHT: 'Night',
    NO_MEDS: 'No medications scheduled for this slot.',
    SCAM_PLACEHOLDER: 'Paste suspicious SMS, bill message or WhatsApp forward here...',
    BILL_ELECTRICITY: 'Electricity Bill',
    BILL_WATER: 'Water Utility Bill',
    BILL_GAS: 'LPG Gas Cylinder',
    BILL_PHONE: 'Mobile & Landline',
    CONFIRM_PIN: 'Enter your 4-digit security PIN',
  },
  ta: {
    APP_NAME: 'ஹம்சஃபர்',
    APP_SUBTITLE: 'முதியோர் பராமரிப்பு தோழன்',
    MEDICINES: 'மருந்துகள்',
    MEDICINES_SUB: 'மருந்து நினைவூட்டல்கள்',
    PAY_BILLS: 'பில் செலுத்துக',
    PAY_BILLS_SUB: 'பாதுகாப்பான பில் செலுத்துதல்',
    CALL_FAMILY: 'குடும்பத்தை அழைக்கவும்',
    CALL_FAMILY_SUB: '1-தொடு வேக அழைப்பு',
    CHECK_SCAM: 'மோசடி சரிபார்ப்பு',
    CHECK_SCAM_SUB: 'AI மோசடி கவசம்',
    SOS: 'அவசர உதவி (SOS)',
    SOS_SUB: 'குடும்பத்திற்கு அவசர எச்சரிக்கை',
    BACK: 'பின்செல்',
    SWITCH_ROLE: 'மாற்று',
    VOICE_ON: 'குரல் இயக்கப்பட்டது',
    VOICE_OFF: 'குரல் அணைக்கப்பட்டது',
    AVAILABLE: 'கிடைக்கிறார்',
    BUSY: 'வேலையில்',
    TAKEN: 'எடுக்கப்பட்டது',
    PENDING: 'நிலுவையில்',
    OVERDUE: 'தாமதமானது',
    SAFE: 'பாதுகாப்பானது',
    SUSPICIOUS: 'சந்தேகத்திற்குரியது',
    CRITICAL: 'ஆபத்தான மோசடி!',
    I_TOOK_IT: 'நான் எடுத்துக்கொண்டேன்',
    TAP_TO_CALL: 'அழைக்கவும்',
    TAP_TO_VIDEO: 'வீடியோ அழைப்பு',
    VERIFY_MESSAGE: 'செய்தியை சரிபார்க்கவும்',
    UPLOAD_PHOTO: 'புகைப்படம் பதிவேற்றவும்',
    PAY_NOW: 'பாதுகாப்பாக செலுத்துங்கள்',
    CANCEL_SOS: 'நான் பாதுகாப்பாக இருக்கிறேன்',
    LISTEN_CMD: 'பேசி தேடுங்கள்',
    ADD_MEDICINE: 'மருந்து சேர்க்கவும்',
    GUARD_CAP: '₹3,000 பாதுகாப்பு வரம்பு செயலில் உள்ளது',
    GREETING: 'வணக்கம்! உங்கள் ஹம்சஃபர் தோழன் தயார்.',
    ALL_SLOTS: 'அனைத்து நேரமும்',
    MORNING: 'காலை',
    AFTERNOON: 'மதியம்',
    EVENING: 'மாலை',
    NIGHT: 'இரவு',
    NO_MEDS: 'இந்த நேரத்தில் மருந்துகள் இல்லை.',
    SCAM_PLACEHOLDER: 'சந்தேகத்திற்கிடமான செய்தியை இங்கே உள்ளிடவும்...',
    BILL_ELECTRICITY: 'மின்சார பில்',
    BILL_WATER: 'குடிநீர் பில்',
    BILL_GAS: 'எரிவாயு சிலிண்டர்',
    BILL_PHONE: 'தொலைபேசி பில்',
    CONFIRM_PIN: 'உங்கள் 4 இலக்க பின்னை உள்ளிடவும்',
  },
  te: {
    APP_NAME: 'హమ్‌సఫర్',
    APP_SUBTITLE: 'వృద్ధుల సంరక్షణ సహచరుడు',
    MEDICINES: 'మందులు',
    MEDICINES_SUB: 'మందుల షెడ్యూల్',
    PAY_BILLS: 'బిల్లులు చెల్లించండి',
    PAY_BILLS_SUB: 'సురక్షిత బిల్లుల చెల్లింపు',
    CALL_FAMILY: 'కుటుంబానికి కాల్ చేయండి',
    CALL_FAMILY_SUB: '1-టచ్ స్పీడ్ డయలర్',
    CHECK_SCAM: 'స్కామ్ తనిఖీ',
    CHECK_SCAM_SUB: 'AI మోసాల రక్షణ',
    SOS: 'అత్యవసర సహాయం (SOS)',
    SOS_SUB: 'కుటుంబానికి అత్యవసర హెచ్చరిక',
    BACK: 'వెనుకకు',
    SWITCH_ROLE: 'మార్చండి',
    VOICE_ON: 'వాయిస్ ఆన్',
    VOICE_OFF: 'వాయిస్ ఆఫ్',
    AVAILABLE: 'అందుబాటులో ఉన్నారు',
    BUSY: 'బిజీగా ఉన్నారు',
    TAKEN: 'తీసుకున్నారు',
    PENDING: 'బాకీ ఉంది',
    OVERDUE: 'సమయం మించిపోయింది',
    SAFE: 'సురక్షితం',
    SUSPICIOUS: 'అనుమానాస్పదం',
    CRITICAL: 'ప్రమాదకరమైన స్కామ్!',
    I_TOOK_IT: 'నేను తీసుకున్నాను',
    TAP_TO_CALL: 'కాల్ చేయండి',
    TAP_TO_VIDEO: 'వీడియో కాల్',
    VERIFY_MESSAGE: 'సందేశాన్ని తనిఖీ చేయండి',
    UPLOAD_PHOTO: 'ఫోటోను అప్‌లోడ్ చేయండి',
    PAY_NOW: 'సురక్షితంగా చెల్లించండి',
    CANCEL_SOS: 'నేను సురక్షితంగా ఉన్నాను',
    LISTEN_CMD: 'మాట్లాడి శోధించండి',
    ADD_MEDICINE: 'మందును జోడించండి',
    GUARD_CAP: '₹3,000 భద్రతా పరిమితి క్రియాశీలకంగా ఉంది',
    GREETING: 'నమస్కారం! మీ హమ్‌సఫర్ సిద్ధంగా ఉంది.',
    ALL_SLOTS: 'అన్ని వేళలా',
    MORNING: 'ఉదయం',
    AFTERNOON: 'మధ్యాహ్నం',
    EVENING: 'సాయంత్రం',
    NIGHT: 'రాత్రి',
    NO_MEDS: 'ఈ సమయానికి మందులు లేవు.',
    SCAM_PLACEHOLDER: 'అనుమానాస్పద సందేశాన్ని ఇక్కడ రాయండి...',
    BILL_ELECTRICITY: 'విద్యుత్ బిల్లు',
    BILL_WATER: 'నీటి బిల్లు',
    BILL_GAS: 'గ్యాస్ సిలిండర్',
    BILL_PHONE: 'ఫోన్ బిల్లు',
    CONFIRM_PIN: 'మీ 4 అంకెల పిన్ నమోదు చేయండి',
  },
  bn: {
    APP_NAME: 'হামসফর',
    APP_SUBTITLE: 'প্রবীণ সেবা সঙ্গী',
    MEDICINES: 'ওষুধ',
    MEDICINES_SUB: 'ওষুধের সময়সূচী',
    PAY_BILLS: 'বিল পরিশোধ',
    PAY_BILLS_SUB: 'নিরাপদ ইউটিলিটি বিল',
    CALL_FAMILY: 'পরিবারকে কল করুন',
    CALL_FAMILY_SUB: '১-টাচ স্পিড ডায়ালার',
    CHECK_SCAM: 'প্রতারণা যাচাই',
    CHECK_SCAM_SUB: 'AI স্ক্যাম সুরক্ষা',
    SOS: 'জরুরী সাহায্য (SOS)',
    SOS_SUB: 'পরিবারকে তাত্ক্ষণিক সতর্কতা',
    BACK: 'ফিরে যান',
    SWITCH_ROLE: 'পরিবর্তন',
    VOICE_ON: 'ভয়েস চালু',
    VOICE_OFF: 'ভয়েস বন্ধ',
    AVAILABLE: 'উপলব্ধ',
    BUSY: 'ব্যস্ত',
    TAKEN: 'নেওয়া হয়েছে',
    PENDING: 'বাকি আছে',
    OVERDUE: 'দেরি হয়েছে',
    SAFE: 'নিরাপদ',
    SUSPICIOUS: 'সন্দেহজনক',
    CRITICAL: 'বিপজ্জনক প্রতারণা!',
    I_TOOK_IT: 'আমি ওষুধ নিয়েছি',
    TAP_TO_CALL: 'কল করুন',
    TAP_TO_VIDEO: 'ভিডিও কল',
    VERIFY_MESSAGE: 'বার্তা পরীক্ষা করুন',
    UPLOAD_PHOTO: 'ছবি আপলোড করুন',
    PAY_NOW: 'নিরাপদে পরিশোধ করুন',
    CANCEL_SOS: 'আমি নিরাপদ আছি',
    LISTEN_CMD: 'বলে খুঁজুন',
    ADD_MEDICINE: 'নতুন ওষুধ যোগ করুন',
    GUARD_CAP: '₹৩,০০০ নিরাপত্তা সীমা সক্রিয়',
    GREETING: 'নমস্কার! আপনার হামসফর প্রস্তুত।',
    ALL_SLOTS: 'সব সময়',
    MORNING: 'সকাল',
    AFTERNOON: 'দুপুর',
    EVENING: 'সন্ধ্যা',
    NIGHT: 'রাত',
    NO_MEDS: 'এই সময়ে কোন ওষুধ নেই।',
    SCAM_PLACEHOLDER: 'সন্দেহজনক মেসেজ এখানে পেস্ট করুন...',
    BILL_ELECTRICITY: 'বিদ্যুৎ বিল',
    BILL_WATER: 'পানির বিল',
    BILL_GAS: 'গ্যাস সিলিন্ডার',
    BILL_PHONE: 'ফোন বিল',
    CONFIRM_PIN: 'আপনার ৪ সংখ্যার পিন লিখুন',
  },
  mr: {
    APP_NAME: 'हमसफर',
    APP_SUBTITLE: 'ज्येष्ठ नागरिक सेवा',
    MEDICINES: 'औषधे',
    MEDICINES_SUB: 'औषध स्मरणपत्रे',
    PAY_BILLS: 'बिल भरा',
    PAY_BILLS_SUB: 'सुरक्षित वीज व पाणी बिल',
    CALL_FAMILY: 'कुटुंबाला कॉल करा',
    CALL_FAMILY_SUB: '१-टच स्पीड डायलर',
    CHECK_SCAM: 'फसवणूक तपासा',
    CHECK_SCAM_SUB: 'AI सुरक्षा कवच',
    SOS: 'तातडीची मदत (SOS)',
    SOS_SUB: 'कुटुंबाला त्वरित अलर्ट पाठवा',
    BACK: 'मागे',
    SWITCH_ROLE: 'बदला',
    VOICE_ON: 'आवाज चालू',
    VOICE_OFF: 'आवाज बंद',
    AVAILABLE: 'उपलब्ध',
    BUSY: 'व्यस्त',
    TAKEN: 'घेतले',
    PENDING: 'बाकी',
    OVERDUE: 'वेळ निघून गेली',
    SAFE: 'सुरक्षित',
    SUSPICIOUS: 'संशयास्पद',
    CRITICAL: 'धोकादायक फसवणूक!',
    I_TOOK_IT: 'मी औषध घेतले',
    TAP_TO_CALL: 'कॉल करा',
    TAP_TO_VIDEO: 'व्हिडिओ कॉल',
    VERIFY_MESSAGE: 'संदेश तपासा',
    UPLOAD_PHOTO: 'फोटो लावा',
    PAY_NOW: 'सुरक्षित पैसे भरा',
    CANCEL_SOS: 'मी सुरक्षित आहे',
    LISTEN_CMD: 'बोलून शोधा',
    ADD_MEDICINE: 'नवीन औषध जोडा',
    GUARD_CAP: '₹३,००० सुरक्षा मर्यादा सक्रिय',
    GREETING: 'नमस्कार! तुमचा हमसफर सज्ज आहे.',
    ALL_SLOTS: 'सर्व वेळा',
    MORNING: 'सकाळ',
    AFTERNOON: 'दुपार',
    EVENING: 'संध्याकाळ',
    NIGHT: 'रात्र',
    NO_MEDS: 'या वेळेसाठी कोणतीही औषधे नाहीत.',
    SCAM_PLACEHOLDER: 'संशयास्पद मेसेज येथे टाका...',
    BILL_ELECTRICITY: 'वीज बिल',
    BILL_WATER: 'पाणी बिल',
    BILL_GAS: 'गॅस सिलिंडर',
    BILL_PHONE: 'फोन बिल',
    CONFIRM_PIN: 'तुमचा ४ आकडी पिन टाका',
  },
  gu: {
    APP_NAME: 'હમસફર',
    APP_SUBTITLE: 'વરિષ્ઠ નાગરિક સેવા',
    MEDICINES: 'દવાઓ',
    MEDICINES_SUB: 'દવાની સમયસારણી',
    PAY_BILLS: 'બિલ ચૂકવો',
    PAY_BILLS_SUB: 'સુરક્ષિત બિલ ચુકવણી',
    CALL_FAMILY: 'કુટુંબને કૉલ કરો',
    CALL_FAMILY_SUB: '૧-ટચ સ્પીડ ડાયલર',
    CHECK_SCAM: 'છેતરપિંડી તપાસો',
    CHECK_SCAM_SUB: 'AI ફ્રોડ સુરક્ષા કવચ',
    SOS: 'કટોકટી સહાય (SOS)',
    SOS_SUB: 'પરિવારને ત્વરિત ચેતવણી',
    BACK: 'પાછા',
    SWITCH_ROLE: 'બદલો',
    VOICE_ON: 'અવાજ ચાલુ',
    VOICE_OFF: 'અવાજ બંધ',
    AVAILABLE: 'ઉપલબ્ધ',
    BUSY: 'વ્યસ્ત',
    TAKEN: 'લીધી છે',
    PENDING: 'બાકી છે',
    OVERDUE: 'સમય વીતી ગયો',
    SAFE: 'સુરક્ષિત',
    SUSPICIOUS: 'શંકાસ્પદ',
    CRITICAL: 'ખતરનાક છેતરપિંડી!',
    I_TOOK_IT: 'મેં દવા લઈ લીધી',
    TAP_TO_CALL: 'કૉલ કરો',
    TAP_TO_VIDEO: 'વીડિયો કૉલ',
    VERIFY_MESSAGE: 'સંદેશ તપાસો',
    UPLOAD_PHOTO: 'ફોટો અપલોડ કરો',
    PAY_NOW: 'સુરક્ષિત ચુકવણી કરો',
    CANCEL_SOS: 'હું સુરક્ષિત છું',
    LISTEN_CMD: 'બોલીને શોધો',
    ADD_MEDICINE: 'નવી દવા ઉમેરો',
    GUARD_CAP: '₹3,000 સુરક્ષા મર્યાદા સક્રિય',
    GREETING: 'નમસ્તે! તમારો હમસફર તૈયાર છે.',
    ALL_SLOTS: 'બધા સમય',
    MORNING: 'સવાર',
    AFTERNOON: 'બપોર',
    EVENING: 'સાંજ',
    NIGHT: 'રાત',
    NO_MEDS: 'આ સમય માટે કોઈ દવા નથી.',
    SCAM_PLACEHOLDER: 'શંકાસ્પદ સંદેશ અહીં લખો...',
    BILL_ELECTRICITY: 'વીજળી બિલ',
    BILL_WATER: 'પાણીનું બિલ',
    BILL_GAS: 'ગેસ સિલિન્ડર',
    BILL_PHONE: 'ફોન બિલ',
    CONFIRM_PIN: 'તમારો ૪ અંકનો પિન દાખલ કરો',
  },
};

interface LanguageContextType {
  language: ShortLangCode;
  langCode: LanguageCode;
  setLanguage: (lang: ShortLangCode | LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'hi',
  langCode: 'hi-IN',
  setLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLangState] = useState<ShortLangCode>('hi');

  useEffect(() => {
    try {
      const stored = localStorage.getItem('humsafar_language');
      if (stored) {
        const shortCode = (stored.includes('-') ? stored.split('-')[0] : stored) as ShortLangCode;
        if (TRANSLATIONS[shortCode]) {
          setLangState(shortCode);
        }
      }
    } catch {
      // Ignore localStorage errors
    }
  }, []);

  const setLanguage = (lang: ShortLangCode | LanguageCode) => {
    const shortCode = (lang.includes('-') ? lang.split('-')[0] : lang) as ShortLangCode;
    if (TRANSLATIONS[shortCode]) {
      setLangState(shortCode);
      try {
        localStorage.setItem('humsafar_language', shortCode);
        window.dispatchEvent(new CustomEvent('humsafar_language_change', { detail: { language: shortCode } }));
      } catch {
        // Ignore localStorage errors
      }
    }
  };

  const bcp47 = `${language}-IN` as LanguageCode;

  const t = (key: string, fallback?: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, langCode: bcp47, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
